# Generated by Django 5.2.1 on 2025-06-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiadmin', '0002_remove_booking_address_remove_booking_booked_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guest_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
